### ISSUE TITLE
Code Improvements Bounty 

### ISSUE THREAD

**Issue by ledgerluminary55** [ledgerluminary55/portfolio#20]
Dear Everyone!

This bounty is available to anyone in the PUMS until this issue is closed.

Look though the code to suggest things that can be improved or fixed. No new features; just fixes or optimizations of existing features. Submit the improvement as a pull request. Each suggestion that is accepted will count for a minimum of 1 hour of work and compensated at the end of the 4 week period in PUMS tokens. The compensation rate is approximately $60/hour depending on the trading price of PUMS. If the team feels the submitted pull request would have required more time they may choose to count it as more than 1 hour in 1 hour increments. You are welcome to tell the team how much time it took, but the final hours will be determined by the team.

The team may decide not to accept your "improvement" pull request, so please communicate in Discord to make sure the team is ok with the improvement before working on it too much.

Best regards.

**Comment by codemedic213515** [comment]
Okay!

**Comment by helios492** [comment]
I can do it.

**Comment by CryptoSmile000** [comment]
no problem😆

**Comment by ledgerluminary55** [comment]
@codemedic213515 
You have to take to this issue
