### ISSUE TITLE
Responsive web design.

### ISSUE THREAD

**Issue by ledgerluminary55** [ledgerluminary55/portfolio#27]
A new release has been detected for https://github.com/AcalaNetwork/chopsticks.
Current version: 0.13.1
Latest version: 1.0.1

Please review the change log and update the documentation accordingly.

**Comment by codemedic213515** [comment]
Okay. Thank you for your effort!

**Comment by helios492** [comment]
I really appreciate your work.

**Comment by CryptoSmile000** [comment]
Thank you for your trouble.
@ledgerluminary55

**Comment by ledgerluminary55** [comment]
@helios492 
you will take this issue.
thx
